DATASET: 
  TRAIN: 'encoder/outputs/vit_xlnet/video'
  VIDEO: 'encoder/outputs/vit_xlnet/video'
  SPLIT_RATIO: 0.95
  VAL: 'encoder/outputs/vit_xlnet/test'
  GT: '/data/wushiwei/data/assistq/assistq_test/test_with_gt.json'
DATALOADER:
  NUM_WORKERS: 4
INPUT:
  QA: 'qa_maskx-1.pth'
  QATEST: 'qa_maskx-1test.pth'
  VIDEO: 'video.pth'
  SCRIPT: 'script.pth'
  PARA: 'paras.pth'
  DIM: 768
  S3DDIM: 512
  NUM_MASKS: 1
MODEL:
  TEXTGROUNDING: 'hard' #combine,hard,soft
  VIDEOGROUNDING: 'hard'
  REWEIGHT: False
  TeacherForce: 'teacherforcing' #'lineardecay'\'autoregression'\'teacherforcing'
  TIMEEMB: False
  ARCH: 'q2a_function'
  DIM_STATE: 768
  NUM_HEADS: 1
  HISTORY: 
    TRAIN: 'gt'
    VAL: 'max'
    ARCH: 'gru'
  FUNCTION_CENTRIC: True # when set to false, is sentence_centric
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 16
  MAX_EPOCHS: 100
CHECK_VAL_EVERY_N_EPOCH: 1
NUM_GPUS: 1
CKPT: ''
INFERENCE: False
BEAM: False
BEAM_SIZE: 1
SSL: False